# Generated by Django 5.0.3 on 2024-03-12 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data_create',
            field=models.DateTimeField(default=datetime.date(2024, 3, 12)),
        ),
        migrations.AddField(
            model_name='category',
            name='data_create',
            field=models.DateTimeField(default=datetime.date(2024, 3, 12)),
        ),
    ]
