# Generated by Django 5.0.3 on 2024-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_data_create_category_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
