# Generated by Django 5.0.3 on 2024-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_data_create_alter_category_data_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('mobile', models.CharField(default='', max_length=20)),
                ('data_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
