# Generated by Django 5.0.3 on 2024-03-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customernew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('تم التوصيل', 'تم التوصيل'), ('جاري التوصيل', 'جاري التوصيل')], max_length=50)),
                ('data_create', models.DateTimeField(auto_now_add=True)),
                ('book', models.ManyToManyField(to='core.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customernew')),
            ],
        ),
    ]
